# Generated by Django 3.0.4 on 2020-06-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0002_delete_product_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='delete_product_list',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
