# Generated by Django 3.0.7 on 2020-06-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0006_addproductlist_supplier_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproductlist',
            name='reason_for_disapproval',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='delete_product_list',
            name='reason_for_disapproval',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
