# Generated by Django 3.0.2 on 2020-06-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_society_corporate_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='videofile',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
