# Generated by Django 2.2.4 on 2020-06-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_videofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
