# Generated by Django 3.0.7 on 2020-06-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200628_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='refunds',
            name='refund_completed',
            field=models.BooleanField(default=False),
        ),
    ]
