# Generated by Django 2.2.4 on 2020-08-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rank',
            field=models.IntegerField(default=10),
        ),
    ]
