# Generated by Django 2.2.4 on 2020-08-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200806_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='package',
            field=models.IntegerField(default=0),
        ),
    ]
